#!/bin/sh

#SBATCH --job-name=2.4_BACr

#SBATCH --output=PWR.o

#SBATCH --error=PWR.error

#SBATCH --partition=savio

#SBATCH --time=10:00:00

#SBATCH --nodes=1

#SBATCH --ntasks-per-node=20

#SBATCH --cpus-per-task=1

# QoS:

#SBATCH --qos=nuclear_savio_normal

#

# Account:

#SBATCH -A co_nuclear

#SBATCH --mail-user=keckler@berkeley.edu
#SBATCH --mail-type=all

# run command
module swap gcc intel
sss2 PWR_assembly -omp 20
